version: '3.6'
services:
  romemu:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - ${AUTH_PORT:-443}:${AUTH_PORT:-443}
      - ${WORLD_PORT:-5555}:${WORLD_PORT:-5555}
      - ${API_PORT:-8080}:${API_PORT:-8080}
      - ${SOCKET_PORT:-8181}:${SOCKET_PORT:-8181}
      - ${FRONT_PORT:-3000}:${FRONT_PORT:-3000}
    command: ["npm", "run", "watch"]
    networks:
      - romemunetwork
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    networks:
      - romemunetwork
networks:
  romemunetwork:
